site_name: eNSPanel Docs
site_url: https://enspanel-docs.andreabaccega.com
repo_url: https://github.com/vekexasia/eNSPanel
repo_name: vekexasia/eNSPanel
theme:
  palette:
    primary: deep purple
  name: material
nav:
  - Home: index.md
  - Getting Started:
    - PCB Ordering: pcb.md
    - Bill Of Material: bom.md
    - Soldering: docs/soldering.md
    - First firmware flash: flashing.md
  - Optional Features:
    - Presence Sensor: presence-sensor.md
    - Buzzer: buzzer.md
    - Microphone: microphone.md 
  - Daughter Boards: daughter.md
  - Known Issues: known-issues.md
