site_name: eNSPanel Docs
site_url: https://enspanel-docs.andreabaccega.com
repo_url: https://github.com/vekexasia/eNSPanel
repo_name: vekexasia/eNSPanel
theme:
  palette:
    primary: deep purple
  name: material
  features:
    - content.code.annotate
    - content.code.copy
markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
nav:
  - Home: index.md
  - Getting Started:
    - PCB Ordering: pcb.md
    - Bill Of Material: bom.md
    - Soldering: soldering.md
    - First firmware flash: flashing.md
  - Modules:
    - Presence Sensor: modules/presence.md
    - Buzzer: modules/buzzer.md
    - Microphone: modules/microphone.md
    - Display: modules/display.md
  - Daughter Boards: daughter.md
  - Known Issues: known-issues.md
