esphome:
  name: sample-esp32
  friendly_name: sample-esp32
  platformio_options:
    board_build.flash_mode: dio
esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

psram:
  mode: octal
  speed: 80MHz

# Enable logging
logger:
  hardware_uart: UART0
  level: DEBUG

# Enable Home Assistant API
api:
  #  reboot_timeout: 0s
  encryption:
    key: "redacted"

ota:
  password: "redacted"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # had issues with output_power not being specified
  output_power: 12dB

web_server:
  port: 80

packages:
  display: !include nextion.yaml
  hmi: !include vekexasia-hmi.yaml
  core: !include core.yaml
  ld: !include ld2410.yaml
  mic: !include microphone.yaml
  buzzer: !include buzzer.yaml
  microwakeword: !include test-microai.yaml

substitutions:
  device_name: sample-thermostat
  friendly_devicename: sample-thermosta
  tft_url: "http://filebrowser-iot.iot/nspanel/pre-babybuddy.tft"
  blank_tft_url: "http://filebrowser-iot.iot/nspanel/nspanel_blank.tft"
  target_temp_home: 19 °C
  target_temp_comfort: 20 °C
