esphome:
  on_boot: 
    priority: -100
    then:
      - micro_wake_word.start:
external_components:
  - source: github://pr#5230
    components: esp_adf
    refresh: 0s
micro_wake_word:
  microphone: mic
  model: hey_jarvis
  on_wake_word_detected:
    - rtttl.play: 'beep:d=16,o=5,b=100:e6'
    - wait_until:
          not:
            rtttl.is_playing:
    #- rtttl.play: "twobits:d=4,o=5,b=220:c6,8g,8g,a,g,p,b,c6"
    - voice_assistant.start:
voice_assistant:
  on_client_connected:
    - micro_wake_word.start:
  on_client_disconnected:
    - micro_wake_word.stop:
  on_error:
    then:
      - rtttl.play: 'beep:d=16,o=5,b=100:e6'
  on_end:
    then:
      - wait_until:
          not:
            voice_assistant.is_running:
      - micro_wake_word.start:  
